// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: common.dto.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocalizedText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Args          []*structpb.Value      `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalizedText) Reset() {
	*x = LocalizedText{}
	mi := &file_common_dto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalizedText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalizedText) ProtoMessage() {}

func (x *LocalizedText) ProtoReflect() protoreflect.Message {
	mi := &file_common_dto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalizedText.ProtoReflect.Descriptor instead.
func (*LocalizedText) Descriptor() ([]byte, []int) {
	return file_common_dto_proto_rawDescGZIP(), []int{0}
}

func (x *LocalizedText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *LocalizedText) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LocalizedText) GetArgs() []*structpb.Value {
	if x != nil {
		return x.Args
	}
	return nil
}

type AppError struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Code             string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	LocalizedMessage *LocalizedText         `protobuf:"bytes,2,opt,name=localized_message,json=localizedMessage,proto3" json:"localized_message,omitempty"`
	Validation       map[string]*AppError   `protobuf:"bytes,3,rep,name=validation,proto3" json:"validation,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AppError) Reset() {
	*x = AppError{}
	mi := &file_common_dto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppError) ProtoMessage() {}

func (x *AppError) ProtoReflect() protoreflect.Message {
	mi := &file_common_dto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppError.ProtoReflect.Descriptor instead.
func (*AppError) Descriptor() ([]byte, []int) {
	return file_common_dto_proto_rawDescGZIP(), []int{1}
}

func (x *AppError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AppError) GetLocalizedMessage() *LocalizedText {
	if x != nil {
		return x.LocalizedMessage
	}
	return nil
}

func (x *AppError) GetValidation() map[string]*AppError {
	if x != nil {
		return x.Validation
	}
	return nil
}

var File_common_dto_proto protoreflect.FileDescriptor

const file_common_dto_proto_rawDesc = "" +
	"\n" +
	"\x10common.dto.proto\x12\x03dto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"a\n" +
	"\rLocalizedText\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12*\n" +
	"\x04args\x18\x03 \x03(\v2\x16.google.protobuf.ValueR\x04args\"\xec\x01\n" +
	"\bAppError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12?\n" +
	"\x11localized_message\x18\x02 \x01(\v2\x12.dto.LocalizedTextR\x10localizedMessage\x12=\n" +
	"\n" +
	"validation\x18\x03 \x03(\v2\x1d.dto.AppError.ValidationEntryR\n" +
	"validation\x1aL\n" +
	"\x0fValidationEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.dto.AppErrorR\x05value:\x028\x01B5Z3github.com/quiz_be/services/core/application/commonb\x06proto3"

var (
	file_common_dto_proto_rawDescOnce sync.Once
	file_common_dto_proto_rawDescData []byte
)

func file_common_dto_proto_rawDescGZIP() []byte {
	file_common_dto_proto_rawDescOnce.Do(func() {
		file_common_dto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_dto_proto_rawDesc), len(file_common_dto_proto_rawDesc)))
	})
	return file_common_dto_proto_rawDescData
}

var file_common_dto_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_dto_proto_goTypes = []any{
	(*LocalizedText)(nil),  // 0: dto.LocalizedText
	(*AppError)(nil),       // 1: dto.AppError
	nil,                    // 2: dto.AppError.ValidationEntry
	(*structpb.Value)(nil), // 3: google.protobuf.Value
}
var file_common_dto_proto_depIdxs = []int32{
	3, // 0: dto.LocalizedText.args:type_name -> google.protobuf.Value
	0, // 1: dto.AppError.localized_message:type_name -> dto.LocalizedText
	2, // 2: dto.AppError.validation:type_name -> dto.AppError.ValidationEntry
	1, // 3: dto.AppError.ValidationEntry.value:type_name -> dto.AppError
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_common_dto_proto_init() }
func file_common_dto_proto_init() {
	if File_common_dto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_dto_proto_rawDesc), len(file_common_dto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_dto_proto_goTypes,
		DependencyIndexes: file_common_dto_proto_depIdxs,
		MessageInfos:      file_common_dto_proto_msgTypes,
	}.Build()
	File_common_dto_proto = out.File
	file_common_dto_proto_goTypes = nil
	file_common_dto_proto_depIdxs = nil
}
