// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: quiz.dto.proto

package dto

import (
	model "github.com/quiz_be/services/core/application/quiz/model"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SelectedQuestionAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuestionId  string `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	AnswerTitle string `protobuf:"bytes,2,opt,name=answer_title,json=answerTitle,proto3" json:"answer_title,omitempty"`
}

func (x *SelectedQuestionAnswer) Reset() {
	*x = SelectedQuestionAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_dto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectedQuestionAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectedQuestionAnswer) ProtoMessage() {}

func (x *SelectedQuestionAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectedQuestionAnswer.ProtoReflect.Descriptor instead.
func (*SelectedQuestionAnswer) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{0}
}

func (x *SelectedQuestionAnswer) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *SelectedQuestionAnswer) GetAnswerTitle() string {
	if x != nil {
		return x.AnswerTitle
	}
	return ""
}

type SubmitAnswerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        string                    `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuizId        string                    `protobuf:"bytes,2,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	SelectAnswers []*SelectedQuestionAnswer `protobuf:"bytes,3,rep,name=select_answers,json=selectAnswers,proto3" json:"select_answers,omitempty"`
}

func (x *SubmitAnswerReq) Reset() {
	*x = SubmitAnswerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_dto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitAnswerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerReq) ProtoMessage() {}

func (x *SubmitAnswerReq) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerReq.ProtoReflect.Descriptor instead.
func (*SubmitAnswerReq) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitAnswerReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitAnswerReq) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *SubmitAnswerReq) GetSelectAnswers() []*SelectedQuestionAnswer {
	if x != nil {
		return x.SelectAnswers
	}
	return nil
}

type SubmitAnswerRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quiz *model.Quiz `protobuf:"bytes,1,opt,name=quiz,proto3" json:"quiz,omitempty"`
}

func (x *SubmitAnswerRes) Reset() {
	*x = SubmitAnswerRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_dto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitAnswerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerRes) ProtoMessage() {}

func (x *SubmitAnswerRes) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerRes.ProtoReflect.Descriptor instead.
func (*SubmitAnswerRes) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitAnswerRes) GetQuiz() *model.Quiz {
	if x != nil {
		return x.Quiz
	}
	return nil
}

type GetLeaderboardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuizId string `protobuf:"bytes,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	Page   int32  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit  int32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetLeaderboardReq) Reset() {
	*x = GetLeaderboardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_dto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLeaderboardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardReq) ProtoMessage() {}

func (x *GetLeaderboardReq) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardReq.ProtoReflect.Descriptor instead.
func (*GetLeaderboardReq) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{3}
}

func (x *GetLeaderboardReq) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *GetLeaderboardReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetLeaderboardReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetLeaderboardRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Leaderboard []*model.Score `protobuf:"bytes,1,rep,name=leaderboard,proto3" json:"leaderboard,omitempty"`
	Page        int32          `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Total       int32          `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *GetLeaderboardRes) Reset() {
	*x = GetLeaderboardRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_dto_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLeaderboardRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardRes) ProtoMessage() {}

func (x *GetLeaderboardRes) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardRes.ProtoReflect.Descriptor instead.
func (*GetLeaderboardRes) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{4}
}

func (x *GetLeaderboardRes) GetLeaderboard() []*model.Score {
	if x != nil {
		return x.Leaderboard
	}
	return nil
}

func (x *GetLeaderboardRes) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetLeaderboardRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetListQuizReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetListQuizReq) Reset() {
	*x = GetListQuizReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_dto_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListQuizReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListQuizReq) ProtoMessage() {}

func (x *GetListQuizReq) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListQuizReq.ProtoReflect.Descriptor instead.
func (*GetListQuizReq) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{5}
}

func (x *GetListQuizReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListQuizReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetListQuizRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListQuiz []*model.Quiz `protobuf:"bytes,1,rep,name=list_quiz,json=listQuiz,proto3" json:"list_quiz,omitempty"`
	Page     int32         `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Total    int32         `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *GetListQuizRes) Reset() {
	*x = GetListQuizRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_dto_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListQuizRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListQuizRes) ProtoMessage() {}

func (x *GetListQuizRes) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListQuizRes.ProtoReflect.Descriptor instead.
func (*GetListQuizRes) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{6}
}

func (x *GetListQuizRes) GetListQuiz() []*model.Quiz {
	if x != nil {
		return x.ListQuiz
	}
	return nil
}

func (x *GetListQuizRes) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListQuizRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetQuizDetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuizId string `protobuf:"bytes,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
}

func (x *GetQuizDetailReq) Reset() {
	*x = GetQuizDetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_dto_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuizDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizDetailReq) ProtoMessage() {}

func (x *GetQuizDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizDetailReq.ProtoReflect.Descriptor instead.
func (*GetQuizDetailReq) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{7}
}

func (x *GetQuizDetailReq) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

type GetQuizDetailRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quiz *model.Quiz `protobuf:"bytes,1,opt,name=quiz,proto3" json:"quiz,omitempty"`
}

func (x *GetQuizDetailRes) Reset() {
	*x = GetQuizDetailRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_dto_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuizDetailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizDetailRes) ProtoMessage() {}

func (x *GetQuizDetailRes) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizDetailRes.ProtoReflect.Descriptor instead.
func (*GetQuizDetailRes) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{8}
}

func (x *GetQuizDetailRes) GetQuiz() *model.Quiz {
	if x != nil {
		return x.Quiz
	}
	return nil
}

type GetUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUserReq) Reset() {
	*x = GetUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_dto_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReq) ProtoMessage() {}

func (x *GetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReq.ProtoReflect.Descriptor instead.
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{9}
}

type GetUserRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListUser []*model.User `protobuf:"bytes,1,rep,name=list_user,json=listUser,proto3" json:"list_user,omitempty"`
}

func (x *GetUserRes) Reset() {
	*x = GetUserRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_dto_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRes) ProtoMessage() {}

func (x *GetUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRes.ProtoReflect.Descriptor instead.
func (*GetUserRes) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserRes) GetListUser() []*model.User {
	if x != nil {
		return x.ListUser
	}
	return nil
}

var File_quiz_dto_proto protoreflect.FileDescriptor

var file_quiz_dto_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x71, 0x75, 0x69, 0x7a, 0x2e, 0x64, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x64, 0x74, 0x6f, 0x1a, 0x15, 0x71, 0x75, 0x69, 0x7a, 0x2f, 0x71, 0x75, 0x69, 0x7a,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5c, 0x0a, 0x16,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x87, 0x01, 0x0a, 0x0f, 0x53,
	0x75, 0x62, 0x6d, 0x69, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x71, 0x75, 0x69, 0x7a, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x71, 0x75, 0x69, 0x7a, 0x49, 0x64,
	0x12, 0x42, 0x0a, 0x0e, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x5f, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x64, 0x74, 0x6f, 0x2e, 0x53,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x0d, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x73, 0x22, 0x32, 0x0a, 0x0f, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x41, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x04, 0x71, 0x75, 0x69, 0x7a, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x51, 0x75,
	0x69, 0x7a, 0x52, 0x04, 0x71, 0x75, 0x69, 0x7a, 0x22, 0x56, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a,
	0x07, 0x71, 0x75, 0x69, 0x7a, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x71, 0x75, 0x69, 0x7a, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x22, 0x6d, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x0b, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x0b, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22,
	0x3a, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x64, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x73, 0x12, 0x28, 0x0a,
	0x09, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x71, 0x75, 0x69, 0x7a, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x08, 0x6c,
	0x69, 0x73, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x22, 0x2b, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x71, 0x75, 0x69, 0x7a, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x71, 0x75, 0x69, 0x7a, 0x49, 0x64, 0x22, 0x33,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x73, 0x12, 0x1f, 0x0a, 0x04, 0x71, 0x75, 0x69, 0x7a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x04, 0x71,
	0x75, 0x69, 0x7a, 0x22, 0x0c, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x22, 0x36, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12,
	0x28, 0x0a, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x08, 0x6c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x71, 0x75, 0x69, 0x7a, 0x5f, 0x62, 0x65, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x71, 0x75, 0x69, 0x7a, 0x2f, 0x64,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_quiz_dto_proto_rawDescOnce sync.Once
	file_quiz_dto_proto_rawDescData = file_quiz_dto_proto_rawDesc
)

func file_quiz_dto_proto_rawDescGZIP() []byte {
	file_quiz_dto_proto_rawDescOnce.Do(func() {
		file_quiz_dto_proto_rawDescData = protoimpl.X.CompressGZIP(file_quiz_dto_proto_rawDescData)
	})
	return file_quiz_dto_proto_rawDescData
}

var file_quiz_dto_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_quiz_dto_proto_goTypes = []interface{}{
	(*SelectedQuestionAnswer)(nil), // 0: dto.SelectedQuestionAnswer
	(*SubmitAnswerReq)(nil),        // 1: dto.SubmitAnswerReq
	(*SubmitAnswerRes)(nil),        // 2: dto.SubmitAnswerRes
	(*GetLeaderboardReq)(nil),      // 3: dto.GetLeaderboardReq
	(*GetLeaderboardRes)(nil),      // 4: dto.GetLeaderboardRes
	(*GetListQuizReq)(nil),         // 5: dto.GetListQuizReq
	(*GetListQuizRes)(nil),         // 6: dto.GetListQuizRes
	(*GetQuizDetailReq)(nil),       // 7: dto.GetQuizDetailReq
	(*GetQuizDetailRes)(nil),       // 8: dto.GetQuizDetailRes
	(*GetUserReq)(nil),             // 9: dto.GetUserReq
	(*GetUserRes)(nil),             // 10: dto.GetUserRes
	(*model.Quiz)(nil),             // 11: model.Quiz
	(*model.Score)(nil),            // 12: model.Score
	(*model.User)(nil),             // 13: model.User
}
var file_quiz_dto_proto_depIdxs = []int32{
	0,  // 0: dto.SubmitAnswerReq.select_answers:type_name -> dto.SelectedQuestionAnswer
	11, // 1: dto.SubmitAnswerRes.quiz:type_name -> model.Quiz
	12, // 2: dto.GetLeaderboardRes.leaderboard:type_name -> model.Score
	11, // 3: dto.GetListQuizRes.list_quiz:type_name -> model.Quiz
	11, // 4: dto.GetQuizDetailRes.quiz:type_name -> model.Quiz
	13, // 5: dto.GetUserRes.list_user:type_name -> model.User
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_quiz_dto_proto_init() }
func file_quiz_dto_proto_init() {
	if File_quiz_dto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_quiz_dto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectedQuestionAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_dto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitAnswerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_dto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitAnswerRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_dto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLeaderboardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_dto_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLeaderboardRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_dto_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListQuizReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_dto_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListQuizRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_dto_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuizDetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_dto_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuizDetailRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_dto_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_dto_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_quiz_dto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_quiz_dto_proto_goTypes,
		DependencyIndexes: file_quiz_dto_proto_depIdxs,
		MessageInfos:      file_quiz_dto_proto_msgTypes,
	}.Build()
	File_quiz_dto_proto = out.File
	file_quiz_dto_proto_rawDesc = nil
	file_quiz_dto_proto_goTypes = nil
	file_quiz_dto_proto_depIdxs = nil
}
