// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: quiz.dto.proto

package dto

import (
	model "github.com/quiz_be/services/core/application/quiz/model"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManageQuizReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuizId        string                 `protobuf:"bytes,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	QuestionIds   []string               `protobuf:"bytes,3,rep,name=question_ids,json=questionIds,proto3" json:"question_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageQuizReq) Reset() {
	*x = ManageQuizReq{}
	mi := &file_quiz_dto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageQuizReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageQuizReq) ProtoMessage() {}

func (x *ManageQuizReq) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageQuizReq.ProtoReflect.Descriptor instead.
func (*ManageQuizReq) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{0}
}

func (x *ManageQuizReq) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *ManageQuizReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ManageQuizReq) GetQuestionIds() []string {
	if x != nil {
		return x.QuestionIds
	}
	return nil
}

type ManageQuestionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Answers       []*model.Answer        `protobuf:"bytes,4,rep,name=answers,proto3" json:"answers,omitempty"`
	CorrectAnswer string                 `protobuf:"bytes,5,opt,name=correct_answer,json=correctAnswer,proto3" json:"correct_answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageQuestionReq) Reset() {
	*x = ManageQuestionReq{}
	mi := &file_quiz_dto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageQuestionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageQuestionReq) ProtoMessage() {}

func (x *ManageQuestionReq) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageQuestionReq.ProtoReflect.Descriptor instead.
func (*ManageQuestionReq) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{1}
}

func (x *ManageQuestionReq) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *ManageQuestionReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ManageQuestionReq) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ManageQuestionReq) GetAnswers() []*model.Answer {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *ManageQuestionReq) GetCorrectAnswer() string {
	if x != nil {
		return x.CorrectAnswer
	}
	return ""
}

type SelectedQuestionAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	AnswerTitle   string                 `protobuf:"bytes,2,opt,name=answer_title,json=answerTitle,proto3" json:"answer_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectedQuestionAnswer) Reset() {
	*x = SelectedQuestionAnswer{}
	mi := &file_quiz_dto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectedQuestionAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectedQuestionAnswer) ProtoMessage() {}

func (x *SelectedQuestionAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectedQuestionAnswer.ProtoReflect.Descriptor instead.
func (*SelectedQuestionAnswer) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{2}
}

func (x *SelectedQuestionAnswer) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *SelectedQuestionAnswer) GetAnswerTitle() string {
	if x != nil {
		return x.AnswerTitle
	}
	return ""
}

type SubmitAnswerReq struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	UserId        string                    `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuizId        string                    `protobuf:"bytes,2,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	SelectAnswers []*SelectedQuestionAnswer `protobuf:"bytes,3,rep,name=select_answers,json=selectAnswers,proto3" json:"select_answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAnswerReq) Reset() {
	*x = SubmitAnswerReq{}
	mi := &file_quiz_dto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAnswerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerReq) ProtoMessage() {}

func (x *SubmitAnswerReq) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerReq.ProtoReflect.Descriptor instead.
func (*SubmitAnswerReq) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitAnswerReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitAnswerReq) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *SubmitAnswerReq) GetSelectAnswers() []*SelectedQuestionAnswer {
	if x != nil {
		return x.SelectAnswers
	}
	return nil
}

type SubmitAnswerRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quiz          *model.Quiz            `protobuf:"bytes,1,opt,name=quiz,proto3" json:"quiz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAnswerRes) Reset() {
	*x = SubmitAnswerRes{}
	mi := &file_quiz_dto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAnswerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerRes) ProtoMessage() {}

func (x *SubmitAnswerRes) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerRes.ProtoReflect.Descriptor instead.
func (*SubmitAnswerRes) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitAnswerRes) GetQuiz() *model.Quiz {
	if x != nil {
		return x.Quiz
	}
	return nil
}

type GetLeaderboardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuizId        string                 `protobuf:"bytes,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardReq) Reset() {
	*x = GetLeaderboardReq{}
	mi := &file_quiz_dto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardReq) ProtoMessage() {}

func (x *GetLeaderboardReq) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardReq.ProtoReflect.Descriptor instead.
func (*GetLeaderboardReq) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{5}
}

func (x *GetLeaderboardReq) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *GetLeaderboardReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetLeaderboardReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetLeaderboardRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leaderboard   []*model.Score         `protobuf:"bytes,1,rep,name=leaderboard,proto3" json:"leaderboard,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardRes) Reset() {
	*x = GetLeaderboardRes{}
	mi := &file_quiz_dto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardRes) ProtoMessage() {}

func (x *GetLeaderboardRes) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardRes.ProtoReflect.Descriptor instead.
func (*GetLeaderboardRes) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{6}
}

func (x *GetLeaderboardRes) GetLeaderboard() []*model.Score {
	if x != nil {
		return x.Leaderboard
	}
	return nil
}

func (x *GetLeaderboardRes) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetLeaderboardRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetListQuizReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListQuizReq) Reset() {
	*x = GetListQuizReq{}
	mi := &file_quiz_dto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListQuizReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListQuizReq) ProtoMessage() {}

func (x *GetListQuizReq) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListQuizReq.ProtoReflect.Descriptor instead.
func (*GetListQuizReq) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{7}
}

func (x *GetListQuizReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListQuizReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetListQuizRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListQuiz      []*model.Quiz          `protobuf:"bytes,1,rep,name=list_quiz,json=listQuiz,proto3" json:"list_quiz,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListQuizRes) Reset() {
	*x = GetListQuizRes{}
	mi := &file_quiz_dto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListQuizRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListQuizRes) ProtoMessage() {}

func (x *GetListQuizRes) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListQuizRes.ProtoReflect.Descriptor instead.
func (*GetListQuizRes) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{8}
}

func (x *GetListQuizRes) GetListQuiz() []*model.Quiz {
	if x != nil {
		return x.ListQuiz
	}
	return nil
}

func (x *GetListQuizRes) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListQuizRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetQuizDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuizId        string                 `protobuf:"bytes,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizDetailReq) Reset() {
	*x = GetQuizDetailReq{}
	mi := &file_quiz_dto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizDetailReq) ProtoMessage() {}

func (x *GetQuizDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizDetailReq.ProtoReflect.Descriptor instead.
func (*GetQuizDetailReq) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{9}
}

func (x *GetQuizDetailReq) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

type GetQuizDetailRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quiz          *model.Quiz            `protobuf:"bytes,1,opt,name=quiz,proto3" json:"quiz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizDetailRes) Reset() {
	*x = GetQuizDetailRes{}
	mi := &file_quiz_dto_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizDetailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizDetailRes) ProtoMessage() {}

func (x *GetQuizDetailRes) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizDetailRes.ProtoReflect.Descriptor instead.
func (*GetQuizDetailRes) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{10}
}

func (x *GetQuizDetailRes) GetQuiz() *model.Quiz {
	if x != nil {
		return x.Quiz
	}
	return nil
}

type GetUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReq) Reset() {
	*x = GetUserReq{}
	mi := &file_quiz_dto_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReq) ProtoMessage() {}

func (x *GetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReq.ProtoReflect.Descriptor instead.
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{11}
}

type GetUserRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListUser      []*model.User          `protobuf:"bytes,1,rep,name=list_user,json=listUser,proto3" json:"list_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRes) Reset() {
	*x = GetUserRes{}
	mi := &file_quiz_dto_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRes) ProtoMessage() {}

func (x *GetUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRes.ProtoReflect.Descriptor instead.
func (*GetUserRes) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserRes) GetListUser() []*model.User {
	if x != nil {
		return x.ListUser
	}
	return nil
}

type GetListQuestionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListQuestionReq) Reset() {
	*x = GetListQuestionReq{}
	mi := &file_quiz_dto_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListQuestionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListQuestionReq) ProtoMessage() {}

func (x *GetListQuestionReq) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListQuestionReq.ProtoReflect.Descriptor instead.
func (*GetListQuestionReq) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{13}
}

func (x *GetListQuestionReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListQuestionReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetListQuestionRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionList  []*model.Question      `protobuf:"bytes,1,rep,name=question_list,json=questionList,proto3" json:"question_list,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListQuestionRes) Reset() {
	*x = GetListQuestionRes{}
	mi := &file_quiz_dto_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListQuestionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListQuestionRes) ProtoMessage() {}

func (x *GetListQuestionRes) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListQuestionRes.ProtoReflect.Descriptor instead.
func (*GetListQuestionRes) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{14}
}

func (x *GetListQuestionRes) GetQuestionList() []*model.Question {
	if x != nil {
		return x.QuestionList
	}
	return nil
}

func (x *GetListQuestionRes) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListQuestionRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_quiz_dto_proto protoreflect.FileDescriptor

const file_quiz_dto_proto_rawDesc = "" +
	"\n" +
	"\x0equiz.dto.proto\x12\x03dto\x1a\x15quiz/quiz.model.proto\"a\n" +
	"\rManageQuizReq\x12\x17\n" +
	"\aquiz_id\x18\x01 \x01(\tR\x06quizId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12!\n" +
	"\fquestion_ids\x18\x03 \x03(\tR\vquestionIds\"\xb4\x01\n" +
	"\x11ManageQuestionReq\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12'\n" +
	"\aanswers\x18\x04 \x03(\v2\r.model.AnswerR\aanswers\x12%\n" +
	"\x0ecorrect_answer\x18\x05 \x01(\tR\rcorrectAnswer\"\\\n" +
	"\x16SelectedQuestionAnswer\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12!\n" +
	"\fanswer_title\x18\x02 \x01(\tR\vanswerTitle\"\x87\x01\n" +
	"\x0fSubmitAnswerReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aquiz_id\x18\x02 \x01(\tR\x06quizId\x12B\n" +
	"\x0eselect_answers\x18\x03 \x03(\v2\x1b.dto.SelectedQuestionAnswerR\rselectAnswers\"2\n" +
	"\x0fSubmitAnswerRes\x12\x1f\n" +
	"\x04quiz\x18\x01 \x01(\v2\v.model.QuizR\x04quiz\"V\n" +
	"\x11GetLeaderboardReq\x12\x17\n" +
	"\aquiz_id\x18\x01 \x01(\tR\x06quizId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"m\n" +
	"\x11GetLeaderboardRes\x12.\n" +
	"\vleaderboard\x18\x01 \x03(\v2\f.model.ScoreR\vleaderboard\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\":\n" +
	"\x0eGetListQuizReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"d\n" +
	"\x0eGetListQuizRes\x12(\n" +
	"\tlist_quiz\x18\x01 \x03(\v2\v.model.QuizR\blistQuiz\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"+\n" +
	"\x10GetQuizDetailReq\x12\x17\n" +
	"\aquiz_id\x18\x01 \x01(\tR\x06quizId\"3\n" +
	"\x10GetQuizDetailRes\x12\x1f\n" +
	"\x04quiz\x18\x01 \x01(\v2\v.model.QuizR\x04quiz\"\f\n" +
	"\n" +
	"GetUserReq\"6\n" +
	"\n" +
	"GetUserRes\x12(\n" +
	"\tlist_user\x18\x01 \x03(\v2\v.model.UserR\blistUser\">\n" +
	"\x12GetListQuestionReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"t\n" +
	"\x12GetListQuestionRes\x124\n" +
	"\rquestion_list\x18\x01 \x03(\v2\x0f.model.QuestionR\fquestionList\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05totalB7Z5github.com/quiz_be/services/core/application/quiz/dtob\x06proto3"

var (
	file_quiz_dto_proto_rawDescOnce sync.Once
	file_quiz_dto_proto_rawDescData []byte
)

func file_quiz_dto_proto_rawDescGZIP() []byte {
	file_quiz_dto_proto_rawDescOnce.Do(func() {
		file_quiz_dto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quiz_dto_proto_rawDesc), len(file_quiz_dto_proto_rawDesc)))
	})
	return file_quiz_dto_proto_rawDescData
}

var file_quiz_dto_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_quiz_dto_proto_goTypes = []any{
	(*ManageQuizReq)(nil),          // 0: dto.ManageQuizReq
	(*ManageQuestionReq)(nil),      // 1: dto.ManageQuestionReq
	(*SelectedQuestionAnswer)(nil), // 2: dto.SelectedQuestionAnswer
	(*SubmitAnswerReq)(nil),        // 3: dto.SubmitAnswerReq
	(*SubmitAnswerRes)(nil),        // 4: dto.SubmitAnswerRes
	(*GetLeaderboardReq)(nil),      // 5: dto.GetLeaderboardReq
	(*GetLeaderboardRes)(nil),      // 6: dto.GetLeaderboardRes
	(*GetListQuizReq)(nil),         // 7: dto.GetListQuizReq
	(*GetListQuizRes)(nil),         // 8: dto.GetListQuizRes
	(*GetQuizDetailReq)(nil),       // 9: dto.GetQuizDetailReq
	(*GetQuizDetailRes)(nil),       // 10: dto.GetQuizDetailRes
	(*GetUserReq)(nil),             // 11: dto.GetUserReq
	(*GetUserRes)(nil),             // 12: dto.GetUserRes
	(*GetListQuestionReq)(nil),     // 13: dto.GetListQuestionReq
	(*GetListQuestionRes)(nil),     // 14: dto.GetListQuestionRes
	(*model.Answer)(nil),           // 15: model.Answer
	(*model.Quiz)(nil),             // 16: model.Quiz
	(*model.Score)(nil),            // 17: model.Score
	(*model.User)(nil),             // 18: model.User
	(*model.Question)(nil),         // 19: model.Question
}
var file_quiz_dto_proto_depIdxs = []int32{
	15, // 0: dto.ManageQuestionReq.answers:type_name -> model.Answer
	2,  // 1: dto.SubmitAnswerReq.select_answers:type_name -> dto.SelectedQuestionAnswer
	16, // 2: dto.SubmitAnswerRes.quiz:type_name -> model.Quiz
	17, // 3: dto.GetLeaderboardRes.leaderboard:type_name -> model.Score
	16, // 4: dto.GetListQuizRes.list_quiz:type_name -> model.Quiz
	16, // 5: dto.GetQuizDetailRes.quiz:type_name -> model.Quiz
	18, // 6: dto.GetUserRes.list_user:type_name -> model.User
	19, // 7: dto.GetListQuestionRes.question_list:type_name -> model.Question
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_quiz_dto_proto_init() }
func file_quiz_dto_proto_init() {
	if File_quiz_dto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quiz_dto_proto_rawDesc), len(file_quiz_dto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_quiz_dto_proto_goTypes,
		DependencyIndexes: file_quiz_dto_proto_depIdxs,
		MessageInfos:      file_quiz_dto_proto_msgTypes,
	}.Build()
	File_quiz_dto_proto = out.File
	file_quiz_dto_proto_goTypes = nil
	file_quiz_dto_proto_depIdxs = nil
}
