// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: quiz.dto.proto

package dto

import (
	model "github.com/quiz_be/services/core/application/quiz/model"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitAnswerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuizId      string `protobuf:"bytes,2,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	QuestionId  string `protobuf:"bytes,3,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	AnswerTitle string `protobuf:"bytes,4,opt,name=answer_title,json=answerTitle,proto3" json:"answer_title,omitempty"`
}

func (x *SubmitAnswerReq) Reset() {
	*x = SubmitAnswerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_dto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitAnswerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerReq) ProtoMessage() {}

func (x *SubmitAnswerReq) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerReq.ProtoReflect.Descriptor instead.
func (*SubmitAnswerReq) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitAnswerReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitAnswerReq) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *SubmitAnswerReq) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *SubmitAnswerReq) GetAnswerTitle() string {
	if x != nil {
		return x.AnswerTitle
	}
	return ""
}

type SubmitAnswerRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quiz *model.Quiz `protobuf:"bytes,1,opt,name=quiz,proto3" json:"quiz,omitempty"`
}

func (x *SubmitAnswerRes) Reset() {
	*x = SubmitAnswerRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_dto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitAnswerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerRes) ProtoMessage() {}

func (x *SubmitAnswerRes) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_dto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerRes.ProtoReflect.Descriptor instead.
func (*SubmitAnswerRes) Descriptor() ([]byte, []int) {
	return file_quiz_dto_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitAnswerRes) GetQuiz() *model.Quiz {
	if x != nil {
		return x.Quiz
	}
	return nil
}

var File_quiz_dto_proto protoreflect.FileDescriptor

var file_quiz_dto_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x71, 0x75, 0x69, 0x7a, 0x2e, 0x64, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x64, 0x74, 0x6f, 0x1a, 0x15, 0x71, 0x75, 0x69, 0x7a, 0x2f, 0x71, 0x75, 0x69, 0x7a,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x87, 0x01, 0x0a,
	0x0f, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x71, 0x75, 0x69,
	0x7a, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x71, 0x75, 0x69, 0x7a,
	0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x5f, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x32, 0x0a, 0x0f, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74,
	0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x04, 0x71, 0x75, 0x69,
	0x7a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x51, 0x75, 0x69, 0x7a, 0x52, 0x04, 0x71, 0x75, 0x69, 0x7a, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x71, 0x75, 0x69, 0x7a, 0x5f, 0x62, 0x65,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x61,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x71, 0x75, 0x69, 0x7a, 0x2f,
	0x64, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_quiz_dto_proto_rawDescOnce sync.Once
	file_quiz_dto_proto_rawDescData = file_quiz_dto_proto_rawDesc
)

func file_quiz_dto_proto_rawDescGZIP() []byte {
	file_quiz_dto_proto_rawDescOnce.Do(func() {
		file_quiz_dto_proto_rawDescData = protoimpl.X.CompressGZIP(file_quiz_dto_proto_rawDescData)
	})
	return file_quiz_dto_proto_rawDescData
}

var file_quiz_dto_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_quiz_dto_proto_goTypes = []interface{}{
	(*SubmitAnswerReq)(nil), // 0: dto.SubmitAnswerReq
	(*SubmitAnswerRes)(nil), // 1: dto.SubmitAnswerRes
	(*model.Quiz)(nil),      // 2: model.Quiz
}
var file_quiz_dto_proto_depIdxs = []int32{
	2, // 0: dto.SubmitAnswerRes.quiz:type_name -> model.Quiz
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_quiz_dto_proto_init() }
func file_quiz_dto_proto_init() {
	if File_quiz_dto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_quiz_dto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitAnswerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_dto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitAnswerRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_quiz_dto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_quiz_dto_proto_goTypes,
		DependencyIndexes: file_quiz_dto_proto_depIdxs,
		MessageInfos:      file_quiz_dto_proto_msgTypes,
	}.Build()
	File_quiz_dto_proto = out.File
	file_quiz_dto_proto_rawDesc = nil
	file_quiz_dto_proto_goTypes = nil
	file_quiz_dto_proto_depIdxs = nil
}
