syntax = "proto3";

option go_package = "github.com/quiz_be/services/core/application/quiz/dto";

import "quiz/quiz.model.proto";

package dto;

message SubmitAnswerReq {
  string user_id = 1;
  string quiz_id = 2;
  string question_id = 3;
  string answer_title = 4;
}

message SubmitAnswerRes {
  model.Quiz quiz = 1;
}

message GetLeaderboardReq {
  string quiz_id = 1;
  int32 page = 2;
  int32 limit = 3;
}

message GetLeaderboardRes {
  repeated model.Score leaderboard = 1;
  int32 page = 2;
  int32 total = 3;
}

message GetListQuizReq {
  int32 page = 1;
  int32 limit = 2;
}

message GetListQuizRes {
  repeated model.Quiz list_quiz = 1;
  int32 page = 2;
  int32 total = 3;
}

message GetQuizDetailReq {
  string quiz_id = 1;
}