syntax = "proto3";

package service;

option go_package = "github.com/quiz_be/services/core/application/quiz/service";

import "quiz/quiz.dto.proto";
import "quiz/quiz.model.proto";
import "google/api/annotations.proto";


service QuizService {
  rpc SubmitAnswer(dto.SubmitAnswerReq) returns (dto.SubmitAnswerRes) {}
  rpc GetLeaderboard(dto.GetLeaderboardReq) returns (dto.GetLeaderboardRes) {
    option (google.api.http) = {
      get: "/v1/quiz/{quiz_id}/leaderboard"
    };
  };
  rpc GetListQuiz(dto.GetListQuizReq) returns (dto.GetListQuizRes) {
    option (google.api.http) = {
      get: "/v1/quiz/list"
    };
  }
  rpc GetQuizDetail(dto.GetQuizDetailReq) returns (model.Quiz) {}
  rpc GetUser(dto.GetUserReq) returns (dto.GetUserRes) {
    option (google.api.http) = {
      get: "/v1/quiz/user"
    };
  }
}
