// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: quiz.service.proto

package service

import (
	dto "github.com/quiz_be/services/core/application/quiz/dto"
	model "github.com/quiz_be/services/core/application/quiz/model"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_quiz_service_proto protoreflect.FileDescriptor

const file_quiz_service_proto_rawDesc = "" +
	"\n" +
	"\x12quiz.service.proto\x12\aservice\x1a\x13quiz/quiz.dto.proto\x1a\x15quiz/quiz.model.proto\x1a\x1cgoogle/api/annotations.proto2\x96\x05\n" +
	"\vQuizService\x12I\n" +
	"\n" +
	"ManageQuiz\x12\x12.dto.ManageQuizReq\x1a\v.model.Quiz\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/quiz/manage\x12Y\n" +
	"\x0eManageQuestion\x12\x16.dto.ManageQuestionReq\x1a\x0f.model.Question\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/question/manage\x12n\n" +
	"\x16GetListQuestionByAdmin\x12\x17.dto.GetListQuestionReq\x1a\x17.dto.GetListQuestionRes\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/question/list-by-admin\x12<\n" +
	"\fSubmitAnswer\x12\x14.dto.SubmitAnswerReq\x1a\x14.dto.SubmitAnswerRes\"\x00\x12h\n" +
	"\x0eGetLeaderboard\x12\x16.dto.GetLeaderboardReq\x1a\x16.dto.GetLeaderboardRes\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/quiz/{quiz_id}/leaderboard\x12N\n" +
	"\vGetListQuiz\x12\x13.dto.GetListQuizReq\x1a\x13.dto.GetListQuizRes\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/quiz/list\x125\n" +
	"\rGetQuizDetail\x12\x15.dto.GetQuizDetailReq\x1a\v.model.Quiz\"\x00\x12B\n" +
	"\aGetUser\x12\x0f.dto.GetUserReq\x1a\x0f.dto.GetUserRes\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/quiz/userB;Z9github.com/quiz_be/services/core/application/quiz/serviceb\x06proto3"

var file_quiz_service_proto_goTypes = []any{
	(*dto.ManageQuizReq)(nil),      // 0: dto.ManageQuizReq
	(*dto.ManageQuestionReq)(nil),  // 1: dto.ManageQuestionReq
	(*dto.GetListQuestionReq)(nil), // 2: dto.GetListQuestionReq
	(*dto.SubmitAnswerReq)(nil),    // 3: dto.SubmitAnswerReq
	(*dto.GetLeaderboardReq)(nil),  // 4: dto.GetLeaderboardReq
	(*dto.GetListQuizReq)(nil),     // 5: dto.GetListQuizReq
	(*dto.GetQuizDetailReq)(nil),   // 6: dto.GetQuizDetailReq
	(*dto.GetUserReq)(nil),         // 7: dto.GetUserReq
	(*model.Quiz)(nil),             // 8: model.Quiz
	(*model.Question)(nil),         // 9: model.Question
	(*dto.GetListQuestionRes)(nil), // 10: dto.GetListQuestionRes
	(*dto.SubmitAnswerRes)(nil),    // 11: dto.SubmitAnswerRes
	(*dto.GetLeaderboardRes)(nil),  // 12: dto.GetLeaderboardRes
	(*dto.GetListQuizRes)(nil),     // 13: dto.GetListQuizRes
	(*dto.GetUserRes)(nil),         // 14: dto.GetUserRes
}
var file_quiz_service_proto_depIdxs = []int32{
	0,  // 0: service.QuizService.ManageQuiz:input_type -> dto.ManageQuizReq
	1,  // 1: service.QuizService.ManageQuestion:input_type -> dto.ManageQuestionReq
	2,  // 2: service.QuizService.GetListQuestionByAdmin:input_type -> dto.GetListQuestionReq
	3,  // 3: service.QuizService.SubmitAnswer:input_type -> dto.SubmitAnswerReq
	4,  // 4: service.QuizService.GetLeaderboard:input_type -> dto.GetLeaderboardReq
	5,  // 5: service.QuizService.GetListQuiz:input_type -> dto.GetListQuizReq
	6,  // 6: service.QuizService.GetQuizDetail:input_type -> dto.GetQuizDetailReq
	7,  // 7: service.QuizService.GetUser:input_type -> dto.GetUserReq
	8,  // 8: service.QuizService.ManageQuiz:output_type -> model.Quiz
	9,  // 9: service.QuizService.ManageQuestion:output_type -> model.Question
	10, // 10: service.QuizService.GetListQuestionByAdmin:output_type -> dto.GetListQuestionRes
	11, // 11: service.QuizService.SubmitAnswer:output_type -> dto.SubmitAnswerRes
	12, // 12: service.QuizService.GetLeaderboard:output_type -> dto.GetLeaderboardRes
	13, // 13: service.QuizService.GetListQuiz:output_type -> dto.GetListQuizRes
	8,  // 14: service.QuizService.GetQuizDetail:output_type -> model.Quiz
	14, // 15: service.QuizService.GetUser:output_type -> dto.GetUserRes
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_quiz_service_proto_init() }
func file_quiz_service_proto_init() {
	if File_quiz_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quiz_service_proto_rawDesc), len(file_quiz_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quiz_service_proto_goTypes,
		DependencyIndexes: file_quiz_service_proto_depIdxs,
	}.Build()
	File_quiz_service_proto = out.File
	file_quiz_service_proto_goTypes = nil
	file_quiz_service_proto_depIdxs = nil
}
